"""empty message

Revision ID: 181efa9673bd
Revises: 51d1037fe42c
Create Date: 2023-03-09 20:45:23.247107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181efa9673bd'
down_revision = '51d1037fe42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('pet_name', sa.String(length=250), nullable=True),
    sa.Column('pet_photo', sa.String(length=500), nullable=True),
    sa.Column('pet_fact', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('pet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
